// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: POS

#include "../ui.h"

void ui_POS_S5_screen_init(void)
{
    ui_POS_S5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_POS_S5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_POS_S5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_POS_S5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMG_S5_BG = lv_img_create(ui_POS_S5);
    lv_img_set_src(ui_IMG_S5_BG, &ui_img_img_bg_1_png);
    lv_obj_set_width(ui_IMG_S5_BG, 272);
    lv_obj_set_height(ui_IMG_S5_BG, 336);
    lv_obj_set_align(ui_IMG_S5_BG, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_IMG_S5_BG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMG_S5_BG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_IMG_S5_BG, 136, 168);

    ui_IMG_Ok_1 = lv_img_create(ui_POS_S5);
    lv_img_set_src(ui_IMG_Ok_1, &ui_img_ok_png);
    lv_obj_set_width(ui_IMG_Ok_1, LV_SIZE_CONTENT);   /// 124
    lv_obj_set_height(ui_IMG_Ok_1, LV_SIZE_CONTENT);    /// 165
    lv_obj_set_x(ui_IMG_Ok_1, 0);
    lv_obj_set_y(ui_IMG_Ok_1, 80);
    lv_obj_set_align(ui_IMG_Ok_1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_IMG_Ok_1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMG_Ok_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_IMG_Ok_1, 62, 62);
    lv_obj_set_style_opa(ui_IMG_Ok_1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMG_Ok_2 = lv_img_create(ui_POS_S5);
    lv_img_set_src(ui_IMG_Ok_2, &ui_img_ok_png);
    lv_obj_set_width(ui_IMG_Ok_2, LV_SIZE_CONTENT);   /// 124
    lv_obj_set_height(ui_IMG_Ok_2, LV_SIZE_CONTENT);    /// 165
    lv_obj_set_x(ui_IMG_Ok_2, 0);
    lv_obj_set_y(ui_IMG_Ok_2, 80);
    lv_obj_set_align(ui_IMG_Ok_2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_IMG_Ok_2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMG_Ok_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_IMG_Ok_2, 62, 62);

    ui_Label_Succesful = lv_label_create(ui_POS_S5);
    lv_obj_set_width(ui_Label_Succesful, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Succesful, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Succesful, 5);
    lv_obj_set_y(ui_Label_Succesful, -267);
    lv_obj_set_align(ui_Label_Succesful, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label_Succesful, "Payment\nSuccesful!");
    lv_obj_set_style_text_color(ui_Label_Succesful, lv_color_hex(0x0B1019), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Succesful, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Succesful, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Succesful, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_press_contimue = lv_label_create(ui_POS_S5);
    lv_obj_set_width(ui_Label_press_contimue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_press_contimue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_press_contimue, 3);
    lv_obj_set_y(ui_Label_press_contimue, -93);
    lv_obj_set_align(ui_Label_press_contimue, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label_press_contimue, "Press to contimue");
    lv_obj_set_style_text_color(ui_Label_press_contimue, lv_color_hex(0x7F848F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_press_contimue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_press_contimue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_press_contimue, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTN_Next_2 = lv_obj_create(ui_POS_S5);
    lv_obj_set_width(ui_BTN_Next_2, 60);
    lv_obj_set_height(ui_BTN_Next_2, 60);
    lv_obj_set_x(ui_BTN_Next_2, 0);
    lv_obj_set_y(ui_BTN_Next_2, -20);
    lv_obj_set_align(ui_BTN_Next_2, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_radius(ui_BTN_Next_2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BTN_Next_2, lv_color_hex(0xFF7A28), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTN_Next_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_BTN_Next_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_BTN_Next_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BTN_Next_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BTN_Next_2, lv_color_hex(0xFF7A28), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_BTN_Next_2, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_BTN_Next_2, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_BTN_Next_2, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_IMG_Arrow1 = lv_img_create(ui_BTN_Next_2);
    lv_img_set_src(ui_IMG_Arrow1, &ui_img_img_arrow_right_png);
    lv_obj_set_width(ui_IMG_Arrow1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_IMG_Arrow1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_IMG_Arrow1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IMG_Arrow1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMG_Arrow1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_BTN_Next_2, ui_event_BTN_Next_2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_POS_S5, ui_event_POS_S5, LV_EVENT_ALL, NULL);

}
