// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: LCD_UI_DISPLAY

#include "../ui.h"

void ui_POS_S1_screen_init(void)
{
    ui_POS_S1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_POS_S1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_POS_S1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_POS_S1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMG_S1_BG = lv_img_create(ui_POS_S1);
    lv_img_set_src(ui_IMG_S1_BG, &ui_img_img_bg_1_png);
    lv_obj_set_width(ui_IMG_S1_BG, 272);
    lv_obj_set_height(ui_IMG_S1_BG, 336);
    lv_obj_set_align(ui_IMG_S1_BG, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_IMG_S1_BG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMG_S1_BG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_IMG_S1_BG, 136, 168);

    ui_Circle_1 = lv_obj_create(ui_POS_S1);
    lv_obj_set_width(ui_Circle_1, 170);
    lv_obj_set_height(ui_Circle_1, 170);
    lv_obj_set_x(ui_Circle_1, 0);
    lv_obj_set_y(ui_Circle_1, -100);
    lv_obj_set_align(ui_Circle_1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Circle_1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Circle_1, lv_color_hex(0xFF7A28), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Circle_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Circle_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Circle_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Circle_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Circle_2 = lv_obj_create(ui_POS_S1);
    lv_obj_set_width(ui_Circle_2, 200);
    lv_obj_set_height(ui_Circle_2, 200);
    lv_obj_set_x(ui_Circle_2, 0);
    lv_obj_set_y(ui_Circle_2, -100);
    lv_obj_set_align(ui_Circle_2, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Circle_2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Circle_2, lv_color_hex(0xFF7A28), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Circle_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Circle_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Circle_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Circle_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Circle_2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMG_POS = lv_img_create(ui_POS_S1);
    lv_img_set_src(ui_IMG_POS, &ui_img_img_pos_png);
    lv_obj_set_width(ui_IMG_POS, 124);
    lv_obj_set_height(ui_IMG_POS, 165);
    lv_obj_set_x(ui_IMG_POS, 0);
    lv_obj_set_y(ui_IMG_POS, 50);
    lv_obj_set_align(ui_IMG_POS, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_IMG_POS, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMG_POS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_card_and_crypto = lv_label_create(ui_POS_S1);
    lv_obj_set_width(ui_Label_card_and_crypto, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_card_and_crypto, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_card_and_crypto, 0);
    lv_obj_set_y(ui_Label_card_and_crypto, -275);
    lv_obj_set_align(ui_Label_card_and_crypto, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label_card_and_crypto, "Solucao\nde Pagamentos");
    lv_obj_set_style_text_color(ui_Label_card_and_crypto, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_card_and_crypto, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_card_and_crypto, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_card_and_crypto, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UNIP = lv_label_create(ui_POS_S1);
    lv_obj_set_width(ui_UNIP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UNIP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UNIP, -1);
    lv_obj_set_y(ui_UNIP, -81);
    lv_obj_set_align(ui_UNIP, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_UNIP, "UNIP TCC");
    lv_obj_set_style_text_color(ui_UNIP, lv_color_hex(0xFF7929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_UNIP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_UNIP, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_UNIP, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Lets_get = lv_label_create(ui_POS_S1);
    lv_obj_set_width(ui_Label_Lets_get, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Lets_get, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Lets_get, -1);
    lv_obj_set_y(ui_Label_Lets_get, -66);
    lv_obj_set_align(ui_Label_Lets_get, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label_Lets_get, "Clique aqui para comecar");
    lv_obj_set_style_text_color(ui_Label_Lets_get, lv_color_hex(0x7F848F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Lets_get, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Lets_get, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Lets_get, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTN_Next = lv_obj_create(ui_POS_S1);
    lv_obj_set_width(ui_BTN_Next, 60);
    lv_obj_set_height(ui_BTN_Next, 60);
    lv_obj_set_align(ui_BTN_Next, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_radius(ui_BTN_Next, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BTN_Next, lv_color_hex(0xFF7A28), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTN_Next, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_BTN_Next, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_BTN_Next, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BTN_Next, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BTN_Next, lv_color_hex(0xFF7A28), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_BTN_Next, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_BTN_Next, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_BTN_Next, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_IMG_Arrow = lv_img_create(ui_BTN_Next);
    lv_img_set_src(ui_IMG_Arrow, &ui_img_img_arrow_right_png);
    lv_obj_set_width(ui_IMG_Arrow, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_IMG_Arrow, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_IMG_Arrow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IMG_Arrow, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMG_Arrow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_BTN_Next, ui_event_BTN_Next, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_POS_S1, ui_event_POS_S1, LV_EVENT_ALL, NULL);

}
